# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "nl"

pipeline:
  - name: WhitespaceTokenizer
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "bert-base-dutch-cased"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# not needed for nlu --> out of scope of this bachelor thesis
# https://rasa.com/docs/rasa/core/policies/
#policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: MappingPolicy
